name: custom_clippers
description: custom_clippers is a package that contains multiple custom clippers and different types of message clippers which you can give to clipper property of ClipPath.

version: 2.0.0
#author: Jagrit Kharbanda<jagritjkh@gmail.com>
homepage: https://github.com/jagritjkh/custom_clippers

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
